apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-ingress
  annotations:
    # If using NGINX:
    kubernetes.io/ingress.class: nginx
    # If using AWS ALB:
    # alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - host: myapp.test.com  # Your custom domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-boot-kubernetes-service
                port:
                  number: 8080